name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: install on linux
      if: startsWith(matrix.os,'ubuntu')
      run: |
          sudo apt-get install libsqlite3-dev unixodbc-dev unixodbc
          sudo cat <<EOT >> /etc/odbcinst.ini
            [SQLite3]
            Description=SQLite3 ODBC Driver
            Driver=libsqlite3odbc.so
            Setup=libsqlite3odbc.so
            UsageCount=1
          EOT
    - uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1.3.0
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Generate docs
      run: crystal doc
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
        SINGLE_COMMIT: true
